services:
  0.4.x:
    build:
      context: .
      target: alpine
      args:
        WS_VERSION: 0.4.x
        PHP_MAJOR_VERSION: '8.2'
        ALPINE_VERSION: '3.18'
      x-bake:
        tags:
          - quay.io/inviqa_images/workspace:0.4.x-dev
  0.3.x:
    build:
      context: .
      target: alpine
      args:
        WS_VERSION: 0.3.x
        PHP_MAJOR_VERSION: '8.1'
        ALPINE_VERSION: '3.17'
        COMPOSE_V1_INSTALL: 'yes'
      x-bake:
        tags:
          - quay.io/inviqa_images/workspace:0.3.x-dev
          - quay.io/inviqa_images/workspace:latest
  0.2.x:
    build:
      context: .
      target: alpine
      args:
        WS_VERSION: 0.2.x
        PHP_MAJOR_VERSION: '8.0'
        ALPINE_VERSION: '3.16'
        COMPOSE_V1_INSTALL: 'yes'
      x-bake:
        tags:
          - quay.io/inviqa_images/workspace:0.2.x-dev

  0.2.x-buster:
    build:
      context: .
      target: buster
      args:
        WS_VERSION: 0.2.x
        PHP_MAJOR_VERSION: '8.0'
        ALPINE_VERSION: '3.16'
        COMPOSE_V1_INSTALL: 'yes'
      x-bake:
        tags:
          - quay.io/inviqa_images/workspace:0.2.x-dev-buster

# build is broken due to transitive dependency requiring union types in PHP
  # 0.1.x:
  #   build:
  #     context: .
  #     target: alpine
  #     args:
  #       WS_VERSION: 0.1.x
  #     x-bake:
  #       tags:
  #         - quay.io/inviqa_images/workspace:0.1.x-dev
